unstable_features = true

array_width = 40
attr_fn_like_width = 80
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
chain_width = 20
combine_control_expr = false
comment_width = 60
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
edition = "2024"
empty_item_single_line = true
enum_discrim_align_threshold = 80
fn_params_layout = "Vertical"
fn_call_width = 80
fn_single_line = true
force_multiline_blocks = false
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
format_macro_bodies = true
skip_macro_invocations = []
format_strings = true
hard_tabs = false
hex_literal_case = "Lower"
show_parse_errors = true
ignore = []
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = false
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 80
merge_derives = true
imports_granularity = "Crate"
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
short_array_element_width_threshold = 8
skip_children = false
single_line_if_else_max_width = 40
single_line_let_else_max_width = 80
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_field_align_threshold = 80
struct_lit_single_line = true
struct_lit_width = 40
tab_spaces = 4
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = false
wrap_comments = true
